import turtle
turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.pencolor("blue")
turtle.pensize(20)
turtle.circle(100)
turtle.penup()
turtle.goto(50,0)
turrle.pendown()
turtle.pencolor("black")
turtle.circle(100)
turtle.penup()

turtle.mainloop()